% Plot a single image of type tmp generated by my cprog with Bassler camera
% this is basically a bmp type file with no header
% Kenneth Laws
% 12/14/2017

function plot_sing_img(imgPath,imgName)

if exist('/Volumes/M2Ext/Test_Drive_0404/')
    imgPath = '/Volumes/M2Ext/Test_Drive_0404/images/';
elseif exist('/media/earthmine/M2Ext/Test_Drive_0404/')
    imgPath = '/media/earthmine/M2Ext/Test_Drive_0404/images/';
else
    error('Image folder not found, update image path in script');
end

imgFile = strcat(imgPath,imgName);

% load in the image
image_1 = load_image_tmp(imgFile);

% plot the first image
figure(1), clf, hold on, colormap gray
pcolor(image_1);
shading interp;
axis equal

% plot a registration line, position doesnt matter as long as tape position
% is clearly readable
plot([200 1000],[100 100],'r');




