function [time, dist, errCnt] = readGpsImu_span(rngfndrPath,rngfndrFile)
%
% Project:      ::     Optical odometer
% Author        ::     Kenneth Laws
%               ::     Here Technologies
% Date Created  ::     12/14/2017
%
% Reads data file generated by the rangefinder (python script)



if nargin < 2
    rngfndrFile = 'AR700.txt';
    
    if exist('/Volumes/M2Ext/Test_Drive_0404/rangefinder/')
    rngfndrPath = '/Volumes/M2Ext/Test_Drive_0404/rangefinder/';
    elseif exist('/media/earthmine/M2Ext/Test_Drive_0404/rangefinder/')
        rngfndrPath = '/media/earthmine/M2Ext/Test_Drive_0404/rangefinder/';
    else
        error('data folder not found, update path in script or plug in external drive');
    end
end


% open the file
fid = fopen([rngfndrPath rngfndrFile]);

% read the data
delimiter = '\t';
startRow = 2;
formatSpec = '%q%q%[^\n\r]';
data = textscan(fid, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
fclose(fid);

% convert the cell arrays to arrays of numbers
% non numeric values are converted to NaN
time = data{1};
dist = data{2};
time = str2double(time);
dist = str2double(dist);

% sum the errors
errCnt = sum(isnan(dist));

end



